import Head from "next/head";
import Link from "next/link";
import {number} from "prop-types";
import Card from "../components/Card";
import styles from "../styles/Home.module.css";


export default function Custom404() {
    return(
        <div>
            <Head>
                <title>404 ERROR</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.pokepage}>
                <div className="bg-gray-400 w-screen justify-items-center pb-7 h-fit grid">
                    <h1 className="text-6xl mt-7 text-gray-700 font-bold">
                        <Link href="/">
                            POKEDEX
                        </Link>
                    </h1>
                </div>
                {/*{pokeList.includes(data.slug)}*/}

                    <div className="bg-gray-400 p-3 mx-auto my-auto rounded-2xl h-100 text-gray-700 text-4xl capitalize">
                        <img src="https://www.svgrepo.com/show/25597/pokemon.svg" className="mb-7"/>
                        This pokemon does not exist
                    </div>

            </main>
        </div>
    );
}