import Head from 'next/head';
import Link from "next/link";
import {useRouter} from "next/router";
import Image from "next/image";
import styles from "../styles/Home.module.css";



export default function Page() {
    const router = useRouter();
    const data = router.query;


    console.log(data)
    // @ts-ignore
    // @ts-ignore
    return(
        <div>
            <Head>
                <title>{data.name}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.pokepage}>
                <div className="bg-gray-400 w-screen justify-items-center pb-7 h-fit grid">
                    <h1 className="text-6xl mt-7 text-gray-700 font-bold">
                        <a href="/">
                            POKEDEX
                        </a>
                    </h1>
                </div>
                <div className="bg-gray-400 p-3 mx-auto my-auto rounded-2xl h-100">
                    <div className="mx-auto">
                        <    // @ts-ignore
                            img src={data.image} className="mx-auto"/>
                    </div>
                    <div className="ml-4 my-auto pl-30 text-2xl pt-3 text-gray-700 capitalize">
                        Name: {data.name}
                        <br/>
                        Weight: { Number(data.w)}
                        <br />
                        Height: { Number(data.h)}
                        <br />
                        Type: {data.type}
                        <br />
                        Abilities: {data.about + " "}
                    </div>
                </div>
            </main>
        </div>
    )}