import Head from 'next/head';
import Link from "next/link";
import {useRouter} from "next/router";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import {number} from "prop-types";
import Card from "../components/Card";


export default function Page() {
    const router = useRouter();
    const data = router.query;

    let o:[] = [];


    for(let i in Object(data.about)){
        // @ts-ignore
        o = [...o,(Object(data.about))[i]]
    }

    console.log(data)
    // @ts-ignore
    // @ts-ignore
    return(
        <div className={styles.container}>
            <Head>
                <title>{data.name}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.pokepage}>
                <div>

                </div>
                <div className="bg-gray-500 w-screen justify-items-center pb-3 h-fit grid">
                    <h1 className={styles.title}>
                        POKEDEX
                    </h1>
                </div>
                <div className="bg-gray-200 p-3 mx-auto my-auto bottom-2 rounded-2xl h-100">
                    <div className="mx-auto">
                        <img src={data.image} className="mx-auto"/>
                    </div>
                    <div className="ml-4 my-auto pl-30 text-2xl capitalize">
                        Name: {data.name}
                        <br/>
                        Weight: { Number(data.w)}
                        <br />
                        Height: { Number(data.h)}
                        <br />
                        Type: {data.type}
                        <br />
                        Abilities: {data.about + " "}
                    </div>
                </div>
            </main>
        </div>

            // @ts-ignore
            // title={data.title}>
            //
            // <div className="grid h-screen place-items-center">
            //
            //
            //     <div className="relative bottom-40 left-50">
            //         <div>
            //                 <img
            //                     // @ts-ignore
            //                     src={data.image}
            //                     // width="200px"
            //                     // height="200px"
            //                     className=" shadow-lg max-w-fit h-60 align-middle border-none undefined bg-grey-800 grid h-50 w-50px place-items-center"
            //                   />
            //                 {/*<Image src={data.image} layout='fill'/>*/}
            //             <h1 className="text-center text-3xl">
            //
            //                 {//@ts-ignore
            //                     (data.title)
            //                 }
            //             </h1>
            //             <hr />
            //         </div>

            //         Abilities:
            //         <br />
            //
            //         {o.map((el:String,index:number) => {
            //
            //             return(
            //                 <div key={index}>
            //                     {el}
            //                     <br />
            //                 </div>
            //             )
            //         })}
            //     </div>
            // </div>


    )}