import Head from 'next/head';
import React, {useState} from 'react';
import Link from "next/link";

const l = ['Normal','Fire','Water','Grass','Electric','Ice','Poison','Fighting','Ground','Flying','Psychic','Bug','Rock','Ghost','Dragon','Dark','Steel','Fairy']

const AppView = ({children, title, pageType}) => {

    const [selectState, setSelectState] = useState(false)

    const onClick = () => {
        setSelectState(!selectState)
    }

    return(

        <React.Fragment>
            <div className='drop-shadow-lg shadow-slate-900'>
                <img src='/bgimg.jpg' className='w-screen h-7 object-cover'/>
            </div>
            <div className='flex items-center justify-items-stretch'>
                <Link href="/">
                    <img src='/pokedex.png' className='h-14 px-5'/>
                </Link>
                <input placeholder='Search pokemons' className=' border rounded-3xl border-gray-700 block w-full h-8 mx-4 my-2 px-4'/>
            </div>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className='flex justify-center'>
                <ul className="flex flex-wrap text-sm font-medium text-center text-gray-500 dark:text-gray-400">
                    {l.map((el:string,index:number) => {
                            return(
                                <li onClick={onClick} className="mx-3 my-2">
                                    <a
                                        href={`/types/${el.toLowerCase()}`}
                                        className={pageType==el.toLowerCase()?"bg-amber-400 inline-block py-3 px-4 rounded-lg hover:text-gray-900 hover:bg-gray-100 dark:hover:bg-gray-800 dark:hover:text-white":"inline-block py-3 px-4 rounded-lg hover:text-gray-900 hover:bg-gray-100 dark:hover:bg-gray-800 dark:hover:text-white"}
                                    >
                                        {el}
                                    </a>
                                </li>
                            )
                        }
                    )}
                    <li onClick={onClick} className="mx-3 my-2">
                        <a
                            href='/'
                            className={pageType?"inline-block py-3 px-4 rounded-lg hover:text-gray-900 hover:bg-gray-100 dark:hover:bg-gray-800 dark:hover:text-white hover:text-white":"inline-block py-3 px-4 rounded-lg hover:text-gray-900 hover:bg-gray-100 dark:hover:bg-gray-800 dark:hover:text-white bg-amber-400 "}
                        >
                            All
                        </a>
                    </li>
                </ul>
            </div>
            {children}
        </React.Fragment>

    )
}



export default AppView;