import Head from 'next/head';
import React from 'react';

const AppView = ({children, title}) => (
    <React.Fragment>
        <div className='drop-shadow-lg shadow-slate-900'>
            <img src='/bgimg.jpg' className='w-screen h-7 object-cover'/>
        </div>
        <div className='flex items-center justify-items-stretch'>
            <img src='/pokedex.png' className='h-14 px-5'/>
            <input placeholder='Search pokemons' className=' border rounded-3xl border-gray-700 block w-full h-8 mx-4 my-2 px-4'/>
        </div>
        <Head>
            <title>{title}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        {children}
    </React.Fragment>
)

export default AppView;